name: Release

on:
  workflow_dispatch:
  push:
    # Publish `1.2.3` tags as releases.
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        if: github.ref != 'refs/heads/master'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
          skipIfReleaseExists: true

  build:
    needs: [release]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ {platform: 'linux/amd64', name: 'x86_64'}, {platform: 'linux/arm64', name: 'aarch64'}]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Build ${{ matrix.arch.platform }}
      run: make PLATFORM=${{ matrix.arch.platform }} one

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./out/zerotier-one-${{ matrix.arch.name }}.tar.gz



